//Categories
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_ERROR_CATEGORIES = 'SET_ERROR_CATEGORIES';
export const SET_LOADING_CATEGORIES = 'SET_LOADING_CATEGORIES';

//Categories By Name
export const SET_CATEGORIES_FILTER = 'SET_CATEGORIES_FILTER';
export const SET_ERROR_CATEGORIES_FILTER = 'SET_ERROR_CATEGORIES_FILTER';
export const SET_LOADING_CATEGORIES_FILTER = 'SET_LOADING_CATEGORIES_FILTER';

// Single Item Showing
export const SET_SINGLE_ITEM = 'SET_SINGLE_ITEM';
export const SET_SINGLE_ITEM_ERROR = 'SET_SINGLE_ITEM_ERROR';
export const SET_SINGLE_ITEM_LOADING = 'SET_SINGLE_ITEM_LOADING';


//Get the Data in Cart 
export const CART_SET_SINGLE_ITEM ='CART_SET_SINGLE_ITEM';
export const CART_SET_SINGLE_ITEM_ERROR ='CART_SET_SINGLE_ITEM_ERROR';
export const CART_SET_SINGLE_ITEM_LOADING ='CART_SET_SINGLE_ITEM_LOADING';
//adding into cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const CLEAR_CART= 'CLEAR_CART';

export const SET_ORDERS = 'SET_ORDERS';
//For API Call
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';